cc_library(
  name = "filament",
  visibility = ["//visibility:public"],
  includes = [
    "include",
  ],
  hdrs = glob([
    "include/**/*.h",
  ]),
  srcs = [
  ],
  deps = [
    "//libs/filabridge",
    # "//libs/filaflat",
    "//libs/utils",
    "//libs/math",
    # "//third_party/smol-v",
  ]
)
