cc_library(
  name = "math",
  visibility = ["//visibility:public"],
  includes = [
    "include",
  ],
  hdrs = glob([
    "include/math/*.h",
  ]),
  srcs = [
    "dummy.cpp",
  ],
  copts = [
  ],
  deps = [
  ]
)
